### ISSUE TITLE
label:question full requirements

### ISSUE THREAD

**Issue by ychaouche** [paralllax/libash#2]
Hello team,

It would be nice to have a list of all the requirements needed to run functions in you library, for example pup and jq for youtube_dl (what is pup ?)

**Comment by paralllax** [comment]
Hi @ychaouche 

Thank you for the comment, great Idea. I agree completely, I'll add that. I suppose that raises the question, if I should include third party tools, or leave everything to be written in native bash.

As far as pup, it's an html parser that can be obtained from here: https://github.com/ericchiang/pup

**Comment by paralllax** [comment]
I've added the requirements section, let me know if you run into anything else!

**Comment by ychaouche** [comment]
Just thank you for being awesome.
